# Generated by Django 5.2.12 on 2026-04-09 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_prescription_id_alter_teamscall_id'),
        ('patients', '0007_alter_conversation_id_alter_inappnotification_id_and_more'),
        ('scheduling', '0002_alter_appointment_id_alter_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_appointments', to='doctor.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_appointments', to='patients.patientprofile'),
        ),
    ]
