# Generated by Django 6.0.1 on 2026-03-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_teamscall"),
        ("doctor", "0003_prescription"),
    ]

    operations = []
