# Generated by Django 5.2.12 on 2026-04-09 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_prescription_id_alter_teamscall_id'),
        ('doctor', '0004_merge_0002_alter_doctorprofile_id_0003_prescription'),
    ]

    operations = [
    ]
