# Generated by Django 6.0.1 on 2026-04-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0005_merge_20260408_2353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="teamscall",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
