# Generated by Django 6.0.1 on 2026-02-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="email_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="lab_result_alerts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="large_text_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="notification_frequency",
            field=models.CharField(default="Daily Summary", max_length=50),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="preferred_language",
            field=models.CharField(default="English", max_length=50),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="sms_alerts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="track_blood_pressure",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="track_weight",
            field=models.BooleanField(default=False),
        ),
    ]
