# Generated by Django 6.0.1 on 2026-02-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patientprofile_email_notifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="electronic_policy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="private_policy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="terms_agreed",
            field=models.BooleanField(default=False),
        ),
    ]
