# Generated by Django 6.0.1 on 2026-02-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_patientprofile_electronic_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="first_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="last_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="phone_number",
            field=models.CharField(default="", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("O+", "O Positive"),
                    ("O-", "O Negative"),
                    ("A+", "A Positive"),
                    ("A-", "A Negative"),
                    ("B+", "B Positive"),
                    ("B-", "B Negative"),
                    ("AB+", "AB Positive"),
                    ("AB-", "AB Negative"),
                ],
                max_length=5,
            ),
        ),
    ]
