# Generated by Django 6.0.1 on 2026-03-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientprofile_email_patientprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='prescription_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
