# Generated by Django 5.2.12 on 2026-03-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientprofile_prescription_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
