# Generated by Django 6.0.1 on 2026-03-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_alter_patientprofile_id"),
        ("patients", "0008_moodentry"),
    ]

    operations = []
