# Generated by Django 5.2.12 on 2026-04-09 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_conversation_id_alter_inappnotification_id_and_more'),
        ('patients', '0009_merge_0006_alter_patientprofile_id_0008_moodentry'),
    ]

    operations = [
    ]
