# Generated by Django 6.0.1 on 2026-04-27 15:07

import uuid
from django.db import migrations, models


def populate_room_names(apps, schema_editor):
    Appointment = apps.get_model("receptionist", "Appointment")
    for appt in Appointment.objects.filter(room_name=""):
        appt.room_name = str(uuid.uuid4())
        appt.save(update_fields=["room_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("receptionist", "0002_appointmentrequest"),
    ]

    operations = [
        # Step 1: add as non-unique with blank default
        migrations.AddField(
            model_name="appointment",
            name="room_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        # Step 2: fill unique UUIDs for any existing rows
        migrations.RunPython(populate_room_names, migrations.RunPython.noop),
        # Step 3: enforce uniqueness
        migrations.AlterField(
            model_name="appointment",
            name="room_name",
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
