# Generated by Django 6.0.1 on 2026-04-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receptionist", "0003_appointment_room_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
    ]
