# Generated by Django 6.0.1 on 2026-04-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receptionist", "0003_meeting_format"),
        ("receptionist", "0005_appointment_is_archived"),
    ]

    operations = []
